# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-02 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=4000)),
            ],
        ),
    ]
